"""
HACK CPU engine for Nand2Tetris — encapsulates all CPU state and execution logic.
"""

RAM_SIZE = 57344  # original spec: 24577 (~24K) words, FPGA spec: 57344 (56K) words

# HACK ALU computation lookup table — all 28 standard computations
# Replaces eval() for bulk execution performance
_COMP = {
    "0":   lambda A, D, M: 0,
    "1":   lambda A, D, M: 1,
    "-1":  lambda A, D, M: -1,
    "D":   lambda A, D, M: D,
    "A":   lambda A, D, M: A,
    "M":   lambda A, D, M: M,
    "!D":  lambda A, D, M: ~D,
    "!A":  lambda A, D, M: ~A,
    "!M":  lambda A, D, M: ~M,
    "-D":  lambda A, D, M: -D,
    "-A":  lambda A, D, M: -A,
    "-M":  lambda A, D, M: -M,
    "D+1": lambda A, D, M: D + 1,
    "A+1": lambda A, D, M: A + 1,
    "M+1": lambda A, D, M: M + 1,
    "D-1": lambda A, D, M: D - 1,
    "A-1": lambda A, D, M: A - 1,
    "M-1": lambda A, D, M: M - 1,
    "D+A": lambda A, D, M: D + A,
    "D+M": lambda A, D, M: D + M,
    "D-A": lambda A, D, M: D - A,
    "D-M": lambda A, D, M: D - M,
    "A-D": lambda A, D, M: A - D,
    "M-D": lambda A, D, M: M - D,
    "D&A": lambda A, D, M: D & A,
    "D&M": lambda A, D, M: D & M,
    "D|A": lambda A, D, M: D | A,
    "D|M": lambda A, D, M: D | M,
    # commutative alternatives (generated by some programs)
    "M+D": lambda A, D, M: M + D,
    "M|D": lambda A, D, M: M | D,
    "A+D": lambda A, D, M: A + D,
    "A|D": lambda A, D, M: A | D,
    "A&D": lambda A, D, M: A & D,
    "M&D": lambda A, D, M: M & D,
}

# HACK jump condition lookup table
_JUMP = {
    "JGT": lambda D: D > 0,
    "JGE": lambda D: D >= 0,
    "JEQ": lambda D: D == 0,
    "JNE": lambda D: D != 0,
    "JLT": lambda D: D < 0,
    "JLE": lambda D: D <= 0,
    "JMP": lambda D: True,
}

ADDRESS_LABELS = {
    # alternate notation
    "R0": 0,  # SP
    "R1": 1,  # LCL
    "R2": 2,  # ARG
    "R3": 3,  # THIS
    "R4": 4,  # THAT
    "R5": 5,  # TEMP
    "R6": 6,  # TEMP
    "R7": 7,  # TEMP
    "R8": 8,  # TEMP
    "R9": 9,  # TEMP
    "R10": 10,  # TEMP
    "R11": 11,  # TEMP
    "R12": 12,  # TEMP
    "BASE": 15,  # R15 (statics assigned at BASE+n, starting at 1 e.g. RAM[16])

    # VM symbols
    "SP": 0,  # segmented by function (saved)
    "LCL": 1,  # segmented by function (saved) -- locals are initialized to zero on call
    "ARG": 2,  # segmented by function (saved) -- args are initialized as passed on call
    "THIS": 3,  # pointer 0 // segmented by function (saved) -- undefined on call
    "THAT": 4,  # pointer 1 // segmented by function (saved) -- undefined on call
    "TEMP": 5,  # 5-12 incl (volatile) -- undefined on call (temp 1-5 are currently unused in compiled VM code)
    "R13": 13,  # reserved for VM translator (volatile) -- variable
    "R14": 14,  # reserved for VM translator (volatile) -- unused
    "R15": 15,  # reserved for VM translator (volatile) -- microcode return address
    "STATIC": 16,  # 16-255 incl (segmented by VM source file, max 240 values)
    "STACK": 256,  # 256-2047 incl (persistent)

    # JACK symbols
    "HEAP": 2048,  # 2048-16383 incl (persistent)
    "IO": 16384,  # 16384-24576 incl (persistent)
    "SCREEN": 16384,  # 16384-24575 incl (persistent)
    "KBD": 24576,  # any RAM address >= 24576 is invalid in HACK ABI

    # FPGA symbols
    # the non-standard behaviour of these ports that don't behave like RAM is not emulated!
    "LED":     4096,
    "BUT":     4097,
    "UART_TX": 4098,
    "UART_RX": 4099,
    "SPI":     4100,
    "SRAM_A":  4101,
    "SRAM_D":  4102,
    "GO":      4103,
    "LCD8":    4104,
    "LCD16":   4105,
    "RTP":     4106,
    "DEBUG0":  4107,
    "DEBUG1":  4108,
    "DEBUG2":  4109,
    "DEBUG3":  4110,
    "DEBUG4":  4111,
}

# New A/C instruction spec:
# original A instructions: 0x0-7FFF (32K words)
# original C instructions: 0x8000-0xFFFF (32K words, 8K reserved)
# new A instructions: 0x0-0xDFFF (56k words)
# new C instructions: 0xE000-FFFF (8K words)

class Engine:
    """HACK CPU engine — encapsulates registers, memory, and instruction execution."""

    def __init__(self, ram_size=RAM_SIZE):
        self.ram = [0] * ram_size
        self.rom_raw = []    # [[src_line, raw_cmd], ...]
        self.rom_debug = []  # [[src_line, debug_cmd], ...]
        self.A = 0
        self.D = 0
        self.pc = 0
        self.halted = False
        self.filepath = None
        self.address_labels = dict(ADDRESS_LABELS)

    @property
    def M(self):
        return self.ram[self.A]

    @M.setter
    def M(self, value):
        self.ram[self.A] = value

    def load(self, asm_filepath):
        """Load an ASM file, resolve symbols, and populate ROM."""
        self.filepath = asm_filepath

        with open(asm_filepath, "r") as f:
            asm_content = f.readlines()

        # symbol & formatting pre-processing
        line = 0
        debug_asm = []
        raw_asm = []
        symbol = False
        pending_comment = None

        for src_line, debug_cmd in enumerate(asm_content, start=1):
            debug_cmd = debug_cmd.strip()  # remove indentation / trailing whitespace
            if debug_cmd == "":
                continue  # empty line
            elif debug_cmd[0] == "/":
                # preserve call/return/function comments for call tree tracking
                if debug_cmd.startswith("// call ") or debug_cmd.startswith("// return") or debug_cmd.startswith("// function "):
                    pending_comment = debug_cmd
                continue  # skip comment lines entirely

            raw_cmd = debug_cmd.split(" //")[0].strip()  # drop comments and strip

            # translate symbols to line numbers (addresses)
            if raw_cmd[0] == "(":
                label_val = raw_cmd[1:-1]  # parse label name i.e. (LABEL)
                symbol = label_val  # store the parsed label name
                if label_val not in self.address_labels:
                    self.address_labels[label_val] = line  # store line (address) for label in dict
                continue  # symbols are parsed out / don't increment line numbers
            else:
                # if a symbol was parsed on previous line append it to this debug line and reset the flag
                if symbol:
                    debug_cmd += " // (%s)" % symbol
                    symbol = False
                # attach pending call/return/function comment
                if pending_comment:
                    debug_cmd += " %s" % pending_comment
                    pending_comment = None
                line += 1

            debug_asm.append([src_line, debug_cmd])  # preserve comments
            raw_asm.append([src_line, raw_cmd])  # code only

        self.rom_raw = raw_asm
        self.rom_debug = debug_asm

    def step(self):
        """Execute one instruction.

        Returns (src_line, raw_cmd, debug_cmd) for the executed instruction.
        Sets self.halted = True on @Sys.halt (instruction is NOT executed).
        Raises RuntimeError on @Sys.error.
        Returns None if already halted or past end of ROM.
        """
        if self.halted or self.pc >= len(self.rom_raw):
            return None

        raw_cmd = self.rom_raw[self.pc][1]
        debug_cmd = self.rom_debug[self.pc][1]
        src_line = self.rom_raw[self.pc][0]

        if self.rom_raw[self.pc][0] != self.rom_debug[self.pc][0]:
            raise ValueError("Engine: Debug/Raw line number mismatch! %s" % self.filepath)

        if raw_cmd[0] == "(":
            raise ValueError("Engine: Symbols should already be parsed out! %s" % self.filepath)

        # escape hatch: break out of Sys.halt infinite loop
        if raw_cmd == "@Sys.halt":
            self.halted = True
            return (src_line, raw_cmd, debug_cmd)

        # trap Sys.error before it enters an infinite loop
        if raw_cmd == "@Sys.error":
            raise RuntimeError("Engine: Sys.error() called @ src_line %d %s" % (src_line, self.filepath))

        # @address assignment
        if raw_cmd[0] == "@":
            label = raw_cmd[1:]
            if label[0].isnumeric():
                self.A = int(label)
            else:
                if label not in self.address_labels:
                    self.address_labels["BASE"] += 1
                    if self.address_labels["BASE"] >= 255:
                        raise OverflowError("Engine: Statics were about to overflow into the stack! %s" % self.filepath)
                    self.address_labels[label] = self.address_labels["BASE"]
                self.A = self.address_labels[label]
            self.pc += 1

        # register assignment dest=comp
        elif "=" in raw_cmd:
            eq = raw_cmd.index("=")
            dst = raw_cmd[:eq]
            result = _COMP[raw_cmd[eq + 1:]](self.A, self.D, self.ram[self.A])
            if "M" in dst:
                self.ram[self.A] = result
            if "A" in dst:
                self.A = result
            if "D" in dst:
                self.D = result
            self.pc += 1

        # jumps comp;jump
        elif ";" in raw_cmd:
            if _JUMP[raw_cmd[2:]](self.D):
                self.pc = self.A
            else:
                self.pc += 1

        else:
            raise ValueError("Engine: Unexpected command: %s %s --- %s %s" % (self.pc, raw_cmd, debug_cmd, self.filepath))

        return (src_line, raw_cmd, debug_cmd)

    def run_cycles(self, n):
        """Execute up to n instruction cycles (optimized bulk execution).

        Uses local variable caching and ALU lookup tables instead of eval() for
        significantly higher throughput than calling step() in a loop.
        Returns the number of cycles actually executed. Stops early on halt or end of ROM.
        """
        # Cache frequently accessed attributes as locals
        pc = self.pc
        A = self.A
        D = self.D
        ram = self.ram
        rom_raw = self.rom_raw
        rom_len = len(rom_raw)
        labels = self.address_labels
        filepath = self.filepath

        cycle = 0
        try:
            while cycle < n:
                if pc >= rom_len:
                    break

                raw_cmd = rom_raw[pc][1]

                # A-instruction (@address / @label)
                if raw_cmd[0] == "@":
                    if raw_cmd == "@Sys.halt":
                        self.halted = True
                        break
                    if raw_cmd == "@Sys.error":
                        raise RuntimeError("Engine: Sys.error() called @ src_line %d %s"
                                           % (rom_raw[pc][0], filepath))

                    label = raw_cmd[1:]
                    if label[0].isnumeric():
                        A = int(label)
                    else:
                        if label not in labels:
                            labels["BASE"] += 1
                            if labels["BASE"] >= 255:
                                raise OverflowError("Engine: Statics overflow! %s" % filepath)
                            labels[label] = labels["BASE"]
                        A = labels[label]
                    pc += 1

                # C-instruction with destination (dest=comp)
                elif "=" in raw_cmd:
                    eq = raw_cmd.index("=")
                    dst = raw_cmd[:eq]
                    result = _COMP[raw_cmd[eq + 1:]](A, D, ram[A])
                    if "M" in dst:
                        ram[A] = result
                    if "A" in dst:
                        A = result
                    if "D" in dst:
                        D = result
                    pc += 1

                # C-instruction with jump (comp;jump)
                elif ";" in raw_cmd:
                    if _JUMP[raw_cmd[2:]](D):
                        pc = A
                    else:
                        pc += 1

                else:
                    raise ValueError("Engine: Unexpected command at pc=%d: %s %s"
                                     % (pc, raw_cmd, filepath))

                cycle += 1
        finally:
            # Always write back locals to self, even on exception
            self.pc = pc
            self.A = A
            self.D = D

        return cycle
